export default {
  SELECT: 'Select',
  NO_SELECT: 'NO-SELECT',
  FROM: 'From',
  TO: 'To',
  SEARCH: 'Search',
  DESCRIPTION_PLACEHOLDER: 'Type Description here',
  PROJECTS: 'Projects',
  WORK_HOURS: 'Total Worked Hours',
  LEAVES: 'Leaves',
  NOT_ALLOWED: 'Not Allowed',
  DUBLICATE_ENTRY_ERROR: 'You have previous same timesheet entry',
  EMPTY_TIMESHEET: 'Empty Timesheet',
  EMPTY_TIMESHEET_MSG: 'Add timesheet before saving',
  OTHER_SKILL_PLACEHOLDER: 'Type other skills here',
};
