ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
use_modular_headers!
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

project 'Intranet', {
  'Debug' => :debug,
  'Release' => :release,
  'StageDebug' => :debug,
  'StageRelease' => :release,
}

target 'Intranet' do
  pod 'GoogleSignIn'

  config = use_native_modules!
  # use_frameworks! :linkage => :static
  # $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'IntranetTests' do
    inherit! :complete
    # Pods for testing
  end

  # Intranet-stage reuses Pods-Intranet (linked in the Xcode target).
  # Do not add a separate CocoaPods target unless pods diverge.

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'

        # Disable Folly coroutines and enable Hermes V1 for all Pods to avoid compile errors
        ['FOLLY_CFG_NO_COROUTINES=1', 'HERMES_V1_ENABLED=1'].each do |definition|
          if config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].nil?
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', definition]
          elsif config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].is_a?(Array)
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << definition unless config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include?(definition)
          else
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = [config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'], definition] unless config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include?(definition)
          end
        end

        ['-DFOLLY_CFG_NO_COROUTINES=1', '-DHERMES_V1_ENABLED=1'].each do |flag|
          if config.build_settings['OTHER_CPLUSPLUSFLAGS'].nil?
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ['$(inherited)', flag]
          elsif config.build_settings['OTHER_CPLUSPLUSFLAGS'].is_a?(Array)
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] << flag unless config.build_settings['OTHER_CPLUSPLUSFLAGS'].include?(flag)
          else
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] = [config.build_settings['OTHER_CPLUSPLUSFLAGS'], flag] unless config.build_settings['OTHER_CPLUSPLUSFLAGS'].include?(flag)
          end
        end
      end
    end

    # Also apply the same flags to the main project targets
    installer.aggregate_targets.each do |target|
      target.user_project.targets.each do |user_target|
        user_target.build_configurations.each do |config|
          config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'

          ['FOLLY_CFG_NO_COROUTINES=1', 'HERMES_V1_ENABLED=1'].each do |definition|
            if config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].nil?
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', definition]
            elsif config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].is_a?(Array)
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << definition unless config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include?(definition)
            else
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = [config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'], definition] unless config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include?(definition)
            end
          end

          ['-DFOLLY_CFG_NO_COROUTINES=1', '-DHERMES_V1_ENABLED=1'].each do |flag|
            if config.build_settings['OTHER_CPLUSPLUSFLAGS'].nil?
              config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ['$(inherited)', flag]
            elsif config.build_settings['OTHER_CPLUSPLUSFLAGS'].is_a?(Array)
              config.build_settings['OTHER_CPLUSPLUSFLAGS'] << flag unless config.build_settings['OTHER_CPLUSPLUSFLAGS'].include?(flag)
            else
              config.build_settings['OTHER_CPLUSPLUSFLAGS'] = [config.build_settings['OTHER_CPLUSPLUSFLAGS'], flag] unless config.build_settings['OTHER_CPLUSPLUSFLAGS'].include?(flag)
            end
          end
        end
      end
      target.user_project.save
    end
  end
end
